IB-77 스토어 영업중 상태 도메인 개발
Inforiginal/inforyou-api-server pull request #68
Opened 2022-10-08 09:18 UTC by dlwlstks96

2022-10-09 07:36 UTC, goyounha11 requested changes
enum을 과거형으로 바꾸고 setOpen은 세터쓰는 느낌이 강하네여 다른 메서드명 고민해버시죵

2022-10-09 11:19 UTC, jinsy731 approved these changes

2022-10-09 11:21 UTC, jinsy731 approved these changes

2022-10-09 11:22 UTC, mumura approved these changes

2022-10-16 07:47 UTC, goyounha11 approved these changes

2022-10-16 07:48 UTC, merged